### ISSUE TITLE
Pull requests back to upstream

### ISSUE THREAD

**Issue by redtide** [milandamen/Discord-IRC-Python#3]
In the `readme` it's stated that pull requests are needed to help the bot development while [here] you said that it's not maintained anymore, so what's the expected action from someone else's fork?

[here]: https://github.com/milandamen/Discord-IRC-Python/issues/2#issuecomment-381217370

**Comment by milandamen** [comment]
You can make your own fork and do whatever with it; there is no need to make a pull request to this repository (unless you want me to review the code and merge it into this repository, which I would gladly do).

I have updated the README to reflect this. Thanks for the notification.

**Comment by redtide** [comment]
I did some changes to adapt to the [new discord.py API]; tested as is the code was not working.
I think I added also some other changes that aren't needed, so I may fork it again and send you only the necessary.
Can you can give a look on my fork and tell me what is not needed (e.g. icon and/or the encoding workaround) or using [this method] maybe? Not sure.

[new discord.py API]: https://discordpy.readthedocs.io/en/latest/migrating.html
[this method]: https://gist.github.com/bhumphrey/3764983

**Comment by milandamen** [comment]
Your changes look fine to me, except I have some question about some changes:

- The encoding change: why are you using latin-1 instead of something like utf-8? I'm not sure if that is supported in that client though.
- The icon: is this something that you made?

If you have a good reason for the encoding change, and if the icon is made by you and you give me permission to use it in this repository, you can just make a pull request here. If not, I would have to do some git magic as you described.

Thanks for giving me a heads up.

**Comment by redtide** [comment]
EDIT: In my case, as it was, the python IRC client crashed when using accented vowels with
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 91: unexpected end of data`. When using UTF-8 it gave wrong characters printed on Discord, but I'm not sure if it will be a problem somewhere else, IDK, so that was just a workaround that works in our channels, not a fix.
The icon is by me, feel free to use it.

**Comment by milandamen** [comment]
Sounds fine to me; please make a pull request.

**Comment by redtide** [comment]
Done, closing.
